name: Format-check
on: [ working-branch ]
jobs:
    build_and_preview:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-node@v2
                with:
                    node-version: '14'
                    cache: 'npm'
            -   run: npm ci && npm run eslint:check && npm run stylelint:check

